[project]
name = "practical-bf"
version = "0.1.0"
description = "HW"
requires-python = ">=3.12,<4.0"

[tool.pdm]
python_requires = ">=3.12"

[tool.pdm.dependencies]
tqdm = "4.66.5"
pandas = "2.2.2"
matplotlib = "3.9.2"
seaborn = "0.13.2"
mygene = "3.2.2"
numpy = "2.1.1"
plotly = "5.24.1"